import { cdnImage } from "./helpers";
import type { MediaItem } from "./types";

export const MEDIA: MediaItem[] = [
  {
    id:      1,
    type:    "image",
    path:    "IMG_7906_pbxspc",
    caption: "Wedding · layout",
    aspect:  "wide",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      2,
    type:    "image",
    path:    "IMG_7904_lswu9f.jpg",
    caption: "Wedding · fatima",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      3,
    type:    "image",
    path:    "IMG_7903_djttay.jpg",
    caption: "Wedding · purple",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      4,
    type:    "image",
    path:    "IMG_7910_dgal5b.jpg",
    caption: "Nature · feet",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      5,
    type:    "image",
    path:    "IMG_7160_pofzex.jpg",
    caption: "Gallery · majesty",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      6,
    type:    "image",
    path:    "IMG_7161_r6dox2.jpg",
    caption: "Gallery · majesty",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      7,
    type:    "image",
    path:    "IMG_7170_emp2cn.jpg",
    caption: "Gallery · majesty",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      8,
    type:    "image",
    path:    "IMG_7174_si8jf0.jpg",
    caption: "Gallery · majesty",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      9,
    type:    "image",
    path:    "IMG_2745_zw8ymu.jpg",
    caption: "Benin · Tattoos",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      10,
    type:    "image",
    path:    "IMG_2773_xjgfiu.jpg",
    caption: "Benin · Tattoos",
    aspect:  "wide",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      11,
    type:    "image",
    path:    "IMG_7909_ptn2ri.jpg",
    caption: "Benin · Plane",
    aspect:  "square",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      12,
    type:    "video",
    path:    "IMG_6966_j9fm4c.mov",
    caption: "Laughter",
    aspect:  "wide",
    poster:  cdnImage("IMG_6966_j9fm4c", "so_0,w_800,q_auto,f_auto"),
    loop:    true,
  },
  {
    id:      13,
    type:    "image",
    path:    "IMG_5678_beosoy.jpg",
    caption: "Abuja · archive",
    aspect:  "square",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      14,
    type:    "image",
    path:    "IMG_7905_eyoyof.jpg",
    caption: "Wedding · bride",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      15,
    type:    "image",
    path:    "IMG_7898_uxjps8.jpg",
    caption: "Outside · stumps",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      16,
    type:    "image",
    path:    "IMG_7901_txpd6m.jpg",
    caption: "Abuja · outside",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      17,
    type:    "image",
    path:    "IMG_7896_eqxpoa.jpg",
    caption: "Abuja · archive",
    aspect:  "tall",
    get lightboxSrc() { return cdnImage(this.path, "w_1600,q_90,f_auto"); },
  },
  {
    id:      18,
    type:    "video",
    path:    "IMG_3273_ctfcxd.mov",
    caption: "Nana",
    aspect:  "wide",
    poster:  cdnImage("IMG_7748_gnq9zc.jpg", "w_800,q_auto,f_auto"),
    loop:    true,
  },
  {
    id:      19,
    type:    "video",
    path:    "IMG_7689_jfqxaf.mov",
    caption: "Eid",
    aspect:  "wide",
    poster:  cdnImage("IMG_7689_jfqxaf", "so_0,w_800,q_auto,f_auto"),
    loop:    true,
  },
  {
    id:      20,
    type:    "video",
    path:    "trim_5DD2C843-B11C-48FA-AA06-8855609B400D_vqikdq.mp4",
    caption: "Eid",
    aspect:  "wide",
    poster:  cdnImage("trim_5DD2C843-B11C-48FA-AA06-8855609B400D_vqikdq.mp4", "so_0,w_800,q_auto,f_auto"),
    loop:    true,
  },
];